import { Food } from '@/lib/types';

export const foods: Food[] = [
  { id: "chicken-breast", nameZh: "鸡胸肉", nameEn: "", category: "meat", nutritionPer100g: { calories:133, protein:31, fat:1.2, carbs:0 }, stance:"eat_more", stanceReason:"高蛋白(31g/100g)、极低脂肪，完美满足增肌和减脂需求", eatMoreFor:{ goals:["muscle_gain","fat_loss"], groups:["健身人群","减脂者","术后恢复"], reason:"最高性价比的纯瘦肉蛋白来源" }, eatLessFor:{ groups:["痛风患者"], risks:[{ risk:"单一饮食营养不均衡", severity:"低", population:"长期只吃鸡胸肉者" }] }, cookingTips:"水煮/煎制(少油)/烤箱/空气炸锅。建议腌制后烹饪改善口感。避免油炸。", nutrientIds:["protein"], aliases:["鸡胸","鸡脯肉"] },
  { id: "beef-lean", nameZh: "瘦牛肉", nameEn: "", category: "meat", nutritionPer100g: { calories:250, protein:26, fat:15, carbs:0 }, stance:"eat_more", stanceReason:"富含蛋白质、肌酸、铁、锌和B12，是天然的运动营养食物", eatMoreFor:{ goals:["muscle_gain","strength"], groups:["力量训练者","缺铁性贫血者"], reason:"天然肌酸来源+高生物价铁" }, eatLessFor:{ groups:["高血脂患者","痛风急性发作期"], risks:[{ risk:"过量红肉增加结直肠癌风险", severity:"中", population:"每日红肉>100g长期食用者" }] }, cookingTips:"选择牛里脊/牛腱等瘦部位。中火快煎保留汁水。避免加工肉制品。", nutrientIds:["protein","creatine","iron"], aliases:["牛肉","beef","牛"] },
  { id: "pork-lean", nameZh: "瘦猪肉", nameEn: "", category: "meat", nutritionPer100g: { calories:143, protein:20, fat:6.2, carbs:0 }, stance:"moderate", stanceReason:"中国最常见肉类，蛋白质含量中等，需注意选择瘦部位", eatMoreFor:{ goals:["muscle_gain"], groups:["一般人群"], reason:"蛋白质来源多样化的好选择" }, eatLessFor:{ groups:["减脂期(热量较高)","高血脂者"], risks:[{ risk:"肥肉高饱和脂肪增加心血管风险", severity:"中", population:"常吃五花肉/排骨者" }] }, cookingTips:"选择猪里脊/猪瘦肉。避免红烧(加大量糖)。优先蒸/煮/快炒。", nutrientIds:["protein","creatine","iron"], aliases:["猪肉","猪瘦肉","猪里脊"] },
  { id: "salmon", nameZh: "三文鱼", nameEn: "", category: "seafood", nutritionPer100g: { calories:208, protein:20, fat:13, carbs:0 }, stance:"eat_more", stanceReason:"优异的Omega-3(EPA+DHA)来源+高质量蛋白+维D", eatMoreFor:{ goals:["muscle_gain","fat_loss"], groups:["所有人","关节保护需求者","心血管健康关注者"], reason:"Omega-3抗炎+维D+优质蛋白质三重功效" }, eatLessFor:{ groups:["痛风患者","鱼过敏者"], risks:[] }, cookingTips:"煎/烤/蒸均可。不要过度烹饪(Omega-3不耐高温)。搭配柠檬汁。", nutrientIds:["protein","omega-3","vitamin-d","creatine"], aliases:["三文鱼","salmon","鲑鱼"] },
  { id: "shrimp", nameZh: "虾", nameEn: "", category: "seafood", nutritionPer100g: { calories:99, protein:24, fat:0.3, carbs:0 }, stance:"eat_more", stanceReason:"极高蛋白质(24g/100g)，极低脂肪，增肌减脂两相宜", eatMoreFor:{ goals:["muscle_gain","fat_loss"], groups:["健身人群"], reason:"超低脂高蛋白，热量仅99kcal/100g" }, eatLessFor:{ groups:["高尿酸/痛风患者","虾过敏者"], risks:[] }, cookingTips:"白灼/清蒸保留最多营养。避免油炸。", nutrientIds:["protein","calcium"], aliases:["虾","虾仁","大虾"] },
  { id: "egg", nameZh: "鸡蛋", nameEn: "", category: "eggs", nutritionPer100g: { calories:144, protein:13, fat:8.8, carbs:2.8 }, stance:"eat_more", stanceReason:"自然界最完美的蛋白质(生物价最高)，富含卵磷脂和多种维生素", eatMoreFor:{ goals:["muscle_gain"], groups:["几乎所有人"], reason:"完整蛋白质+卵磷脂+胆碱+脂溶性维生素，营养密度极高" }, eatLessFor:{ groups:["严重高胆固醇血症者(可只吃蛋白)","鸡蛋过敏者"], risks:[{ risk:"多数人膳食胆固醇不影响血胆固醇", severity:"低", population:"一般人群" }] }, cookingTips:"水煮蛋营养保留最好。每天1-3个对健康人群安全。", nutrientIds:["protein","vitamin-d","omega-3"], aliases:["鸡蛋","蛋","egg"] },
  { id: "tofu", nameZh: "豆腐", nameEn: "", category: "legumes", nutritionPer100g: { calories:76, protein:8, fat:4.8, carbs:1.9 }, stance:"eat_more", stanceReason:"最佳植物蛋白来源之一，含大豆异黄酮和丰富钙质", eatMoreFor:{ goals:["muscle_gain","fat_loss"], groups:["素食者","乳糖不耐受者","减脂者"], reason:"低热量高蛋白+钙含量高" }, eatLessFor:{ groups:["严重甲状腺功能减退未治疗者"], risks:[] }, cookingTips:"北豆腐(老豆腐)蛋白含量最高。避免深度油炸(油豆腐热量极高)。", nutrientIds:["protein","calcium","iron"], aliases:["豆腐","tofu"] },
  { id: "broccoli", nameZh: "西兰花", nameEn: "", category: "vegetables", nutritionPer100g: { calories:34, protein:2.8, fat:0.4, carbs:7, fiber:2.6 }, stance:"eat_more", stanceReason:"营养密度极高的十字花科蔬菜，维生素C含量超橘子", eatMoreFor:{ goals:["muscle_gain","fat_loss"], groups:["所有人"], reason:"低热量高纤维+强抗氧化+多种维生素矿物质" }, eatLessFor:{ groups:["服用抗凝药(华法林)者","甲减未治疗者(大量生吃)"], risks:[] }, cookingTips:"短时间蒸(3-4分钟)保留最多营养。避免长时间水煮。", nutrientIds:["vitamin-c","calcium","iron"], aliases:["西兰花","青花菜"] },
  { id: "spinach", nameZh: "菠菜", nameEn: "", category: "vegetables", nutritionPer100g: { calories:23, protein:2.9, fat:0.4, carbs:3.6, fiber:2.2 }, stance:"eat_more", stanceReason:"铁、钙、镁、维K的天然来源，植物化学物丰富", eatMoreFor:{ goals:["muscle_gain"], groups:["贫血风险者","素食者"], reason:"高植物铁+高镁(抗肌肉抽筋)" }, eatLessFor:{ groups:["肾结石易感者(草酸盐高)","服用抗凝药者"], risks:[] }, cookingTips:"焯水30秒去除大部分草酸再烹饪。搭配富含维C食材提高铁吸收。", nutrientIds:["iron","calcium"], aliases:["菠菜"] },
  { id: "banana", nameZh: "香蕉", nameEn: "", category: "fruits", nutritionPer100g: { calories:93, protein:1.1, fat:0.3, carbs:23, fiber:2.6 }, stance:"eat_more", stanceReason:"天然快速能量来源，富含钾和镁，训练前后理想食物", eatMoreFor:{ goals:["muscle_gain","endurance","strength"], groups:["训练量大者","易抽筋者"], reason:"快速碳水+钾镁(防止抽筋)" }, eatLessFor:{ groups:["糖尿病患者(控制分量)"], risks:[] }, cookingTips:"训练前30-60分钟吃一根。搭配蛋白质做训练后恢复餐。", nutrientIds:["carbohydrates"], aliases:["香蕉","banana"] },
  { id: "kiwi", nameZh: "猕猴桃", nameEn: "", category: "fruits", nutritionPer100g: { calories:61, protein:1.1, fat:0.5, carbs:15, fiber:3 }, stance:"eat_more", stanceReason:"维生素C含量极高(超橙子2倍)，高膳食纤维，抗氧化丰富", eatMoreFor:{ goals:["muscle_gain"], groups:["所有人","素食者(提高铁吸收)"], reason:"维C提高植物铁吸收+抗氧化+助消化" }, eatLessFor:{ groups:["猕猴桃过敏者"], risks:[] }, cookingTips:"直接食用或加入酸奶/蛋白奶昔。", nutrientIds:["vitamin-c"], aliases:["猕猴桃","奇异果"] },
  { id: "orange", nameZh: "橙子", nameEn: "", category: "fruits", nutritionPer100g: { calories:47, protein:0.9, fat:0.1, carbs:12, fiber:2.4 }, stance:"eat_more", stanceReason:"经典维C水果，便宜易得", eatMoreFor:{ goals:["muscle_gain"], groups:["所有人"], reason:"维C+类黄酮抗氧化+低热量" }, eatLessFor:{ groups:["胃酸过多/胃食管反流者"], risks:[] }, cookingTips:"直接食用比喝果汁好(保留纤维)。不要空腹大量食用。", nutrientIds:["vitamin-c"], aliases:["橙子","橘子"] },
  { id: "rice", nameZh: "白米饭", nameEn: "", category: "grains", nutritionPer100g: { calories:130, protein:2.7, fat:0.3, carbs:28, fiber:0.4 }, stance:"moderate", stanceReason:"中国主食，提供快速能量但升糖指数高，需要注意份量", eatMoreFor:{ goals:["muscle_gain"], groups:["高强度训练者(训练后补充糖原)"], reason:"训练后快速补充肌糖原" }, eatLessFor:{ groups:["减脂期","糖尿病/血糖控制","久坐少动者"], risks:[{ risk:"高GI导致血糖波动、饥饿感快", severity:"中", population:"不控制份量的减脂人群" }] }, cookingTips:"米饭冷却后部分淀粉转化为抗性淀粉。搭配蛋白质和蔬菜一起降低GI。", nutrientIds:["carbohydrates"], aliases:["米饭","大米","白饭"] },
  { id: "oats", nameZh: "燕麦", nameEn: "", category: "grains", nutritionPer100g: { calories:389, protein:16.9, fat:6.9, carbs:66, fiber:10.6 }, stance:"eat_more", stanceReason:"全谷物中蛋白质含量最高(17g/100g)，高纤维(β-葡聚糖)，缓释能量", eatMoreFor:{ goals:["muscle_gain","fat_loss"], groups:["减脂者","心血管健康关注者"], reason:"缓释碳水+高蛋白质+降胆固醇三合一" }, eatLessFor:{ groups:[], risks:[] }, cookingTips:"隔夜燕麦(冷泡)保留最多营养。加蛋白粉和水果做训练前餐。", nutrientIds:["carbohydrates","protein"], aliases:["燕麦","oats"] },
  { id: "sweet-potato", nameZh: "红薯", nameEn: "", category: "grains", nutritionPer100g: { calories:86, protein:1.6, fat:0.1, carbs:20, fiber:3 }, stance:"eat_more", stanceReason:"低GI复合碳水，极高维生素A(β-胡萝卜素)，富含抗氧化物质", eatMoreFor:{ goals:["muscle_gain","fat_loss"], groups:["减脂代替米饭者"], reason:"缓释能量+低GI+高纤维+高维A" }, eatLessFor:{ groups:[], risks:[] }, cookingTips:"蒸/烤/煮均可。紫薯花青素含量更高。", nutrientIds:["carbohydrates"], aliases:["红薯","地瓜","番薯"] },
  { id: "milk", nameZh: "牛奶", nameEn: "", category: "dairy", nutritionPer100g: { calories:66, protein:3.2, fat:3.6, carbs:4.8 }, stance:"eat_more", stanceReason:"最易得的优质蛋白质+钙来源，含天然乳清和酪蛋白", eatMoreFor:{ goals:["muscle_gain","strength"], groups:["骨质疏松风险者","健身人群"], reason:"优质蛋白+高吸收率钙+强化维D" }, eatLessFor:{ groups:["乳糖不耐受者(改喝无乳糖奶)","牛奶蛋白过敏者"], risks:[] }, cookingTips:"训练后巧克力奶是天然恢复饮品。乳糖不耐者选无乳糖牛奶或酸奶替代。", nutrientIds:["protein","calcium","vitamin-d"], aliases:["牛奶","牛乳","鲜奶"] },
  { id: "walnut", nameZh: "核桃", nameEn: "", category: "nuts", nutritionPer100g: { calories:654, protein:15, fat:65, carbs:14, fiber:6.7 }, stance:"moderate", stanceReason:"富含植物性Omega-3(ALA)和抗氧化物质，但热量密度极高", eatMoreFor:{ goals:["muscle_gain"], groups:["心血管健康关注者","脑力劳动者"], reason:"植物Omega-3(ALA)+多酚抗氧化" }, eatLessFor:{ groups:["减脂期(严格控热)"], risks:[{ risk:"极高热量易超标", severity:"中", population:"不控制份量者" }] }, cookingTips:"每日一小把(约30g≈200大卡)。加入燕麦/酸奶。", nutrientIds:["omega-3"], aliases:["核桃","胡桃"] },
  { id: "avocado", nameZh: "牛油果", nameEn: "", category: "fruits", nutritionPer100g: { calories:160, protein:2, fat:15, carbs:9, fiber:6.7 }, stance:"moderate", stanceReason:"优质不饱和脂肪+高纤维+高钾，但热量密度高需控制", eatMoreFor:{ goals:["muscle_gain"], groups:["低脂饮食者(增加健康脂肪)","心血管健康关注者"], reason:"单不饱和脂肪降胆固醇+高钾降血压" }, eatLessFor:{ groups:["严格减脂期"], risks:[] }, cookingTips:"每天半个即可。搭配全麦吐司做早餐。", nutrientIds:["fat"], aliases:["牛油果","鳄梨"] },
  { id: "olive-oil", nameZh: "橄榄油", nameEn: "", category: "seasoning", nutritionPer100g: { calories:884, protein:0, fat:100, carbs:0 }, stance:"eat_more", stanceReason:"健康的单不饱和脂肪来源，富含抗氧化多酚，地中海饮食核心", eatMoreFor:{ goals:["muscle_gain"], groups:["所有烹饪用油替换者","心血管健康"], reason:"替代动物脂肪明显降低心血管风险" }, eatLessFor:{ groups:["严格减脂(替代不是额外添加)"], risks:[] }, cookingTips:"初榨橄榄油适合凉拌/低温烹饪。高温煎炸选精炼橄榄油。避光保存。", nutrientIds:["fat"], aliases:["橄榄油"] },
  { id: "strawberry", nameZh: "草莓", nameEn: "", category: "fruits", nutritionPer100g: { calories:32, protein:0.7, fat:0.3, carbs:7.7, fiber:2 }, stance:"eat_more", stanceReason:"低热量高维C，抗氧化花青素丰富", eatMoreFor:{ goals:["muscle_gain","fat_loss"], groups:["所有人"], reason:"低热量+维C+多酚抗氧化组合" }, eatLessFor:{ groups:[], risks:[] }, cookingTips:"直接食用或搭配酸奶/蛋白奶昔。不过度清洗(水溶性营养流失)。", nutrientIds:["vitamin-c"], aliases:["草莓","strawberry"] },
];

