import { Muscle } from '@/lib/types';

export const muscles: Muscle[] = [
  { id: "pectoralis-major", nameZh: "胸大肌", nameEn: "Pectoralis Major", nameLa: "Musculus pectoralis major", group: "chest", layer: "superficial", origin: "锁骨内侧半、胸骨前面、第1-6肋软骨", insertion: "肱骨大结节嵴", function: ["肩关节内收","肩关节内旋","肩关节屈曲"], exerciseIds: ["barbell-bench-press","dumbbell-fly","cable-crossover","push-up","incline-dumbbell-press"], relatedNutrientIds: ["protein","creatine"], aliases: ["胸肌","pec","chest"], meshNames: [] },
  { id: "pectoralis-minor", nameZh: "胸小肌", nameEn: "Pectoralis Minor", nameLa: "Musculus pectoralis minor", group: "chest", layer: "deep", origin: "第3-5肋骨前面", insertion: "肩胛骨喙突", function: ["下拉肩胛骨","前伸肩胛骨"], exerciseIds: ["push-up","dip"], relatedNutrientIds: ["protein"], aliases: ["胸小"], meshNames: [] },
  { id: "latissimus-dorsi", nameZh: "背阔肌", nameEn: "Latissimus Dorsi", nameLa: "Musculus latissimus dorsi", group: "back", layer: "superficial", origin: "T7-L5棘突、骶骨、髂嵴", insertion: "肱骨小结节嵴", function: ["肩关节内收","肩关节伸展","肩关节内旋"], exerciseIds: ["pull-up","lat-pulldown","barbell-row"], relatedNutrientIds: ["protein","creatine"], aliases: ["背阔","lats"], meshNames: [] },
  { id: "trapezius", nameZh: "斜方肌", nameEn: "Trapezius", nameLa: "Musculus trapezius", group: "back", layer: "superficial", origin: "枕外隆凸、C7-T12棘突", insertion: "锁骨外侧1/3、肩峰、肩胛冈", function: ["肩胛骨上提","肩胛骨内收","肩胛骨下压"], exerciseIds: ["barbell-shrug","face-pull","deadlift"], relatedNutrientIds: ["protein"], aliases: ["斜方","traps"], meshNames: [] },
  { id: "erector-spinae", nameZh: "竖脊肌", nameEn: "Erector Spinae", nameLa: "Musculus erector spinae", group: "back", layer: "deep", origin: "骶骨、髂嵴、腰椎棘突", insertion: "肋骨、胸椎横突", function: ["脊柱伸展","脊柱侧屈"], exerciseIds: ["deadlift","barbell-row"], relatedNutrientIds: ["protein"], aliases: ["竖脊","下背"], meshNames: [] },
  { id: "deltoid-anterior", nameZh: "三角肌前束", nameEn: "Anterior Deltoid", nameLa: "Musculus deltoideus pars clavicularis", group: "shoulders", layer: "superficial", origin: "锁骨外侧1/3", insertion: "肱骨三角肌粗隆", function: ["肩关节屈曲","肩关节内旋"], exerciseIds: ["overhead-press","barbell-bench-press"], relatedNutrientIds: ["protein"], aliases: ["前束","front delt"], meshNames: [] },
  { id: "deltoid-lateral", nameZh: "三角肌中束", nameEn: "Lateral Deltoid", nameLa: "Musculus deltoideus pars acromialis", group: "shoulders", layer: "superficial", origin: "肩峰", insertion: "肱骨三角肌粗隆", function: ["肩关节外展"], exerciseIds: ["lateral-raise","overhead-press"], relatedNutrientIds: ["protein"], aliases: ["中束","side delt"], meshNames: [] },
  { id: "deltoid-posterior", nameZh: "三角肌后束", nameEn: "Posterior Deltoid", nameLa: "Musculus deltoideus pars spinalis", group: "shoulders", layer: "superficial", origin: "肩胛冈", insertion: "肱骨三角肌粗隆", function: ["肩关节伸展","肩关节外旋"], exerciseIds: ["face-pull","reverse-fly"], relatedNutrientIds: ["protein"], aliases: ["后束","rear delt"], meshNames: [] },
  { id: "biceps-brachii", nameZh: "肱二头肌", nameEn: "Biceps Brachii", nameLa: "Musculus biceps brachii", group: "arms", layer: "superficial", origin: "长头:肩胛骨盂上结节;短头:肩胛骨喙突", insertion: "桡骨粗隆", function: ["肘关节屈曲","前臂旋后"], exerciseIds: ["barbell-curl","dumbbell-curl","hammer-curl"], relatedNutrientIds: ["protein","creatine"], aliases: ["二头","biceps"], meshNames: [] },
  { id: "triceps-brachii", nameZh: "肱三头肌", nameEn: "Triceps Brachii", nameLa: "Musculus triceps brachii", group: "arms", layer: "superficial", origin: "长头:肩胛骨盂下结节;侧头+内头:肱骨后面", insertion: "尺骨鹰嘴", function: ["肘关节伸展"], exerciseIds: ["tricep-pushdown","dip","skull-crusher"], relatedNutrientIds: ["protein"], aliases: ["三头","triceps"], meshNames: [] },
  { id: "brachialis", nameZh: "肱肌", nameEn: "Brachialis", nameLa: "Musculus brachialis", group: "arms", layer: "deep", origin: "肱骨前下半部", insertion: "尺骨粗隆", function: ["肘关节屈曲"], exerciseIds: ["hammer-curl"], relatedNutrientIds: ["protein"], aliases: [], meshNames: [] },
  { id: "rectus-abdominis", nameZh: "腹直肌", nameEn: "Rectus Abdominis", nameLa: "Musculus rectus abdominis", group: "core", layer: "superficial", origin: "耻骨嵴", insertion: "第5-7肋软骨、剑突", function: ["脊柱屈曲","骨盆后倾"], exerciseIds: ["crunch","plank","cable-crunch"], relatedNutrientIds: ["protein"], aliases: ["腹肌","abs"], meshNames: [] },
  { id: "obliques", nameZh: "腹斜肌群", nameEn: "Obliques", nameLa: "Musculi obliqui abdominis", group: "core", layer: "superficial", origin: "外斜:下8肋;内斜:髂嵴", insertion: "外斜:髂嵴;内斜:下3肋", function: ["脊柱侧屈","脊柱旋转"], exerciseIds: ["russian-twist","side-plank"], relatedNutrientIds: ["protein"], aliases: ["侧腹","oblique"], meshNames: [] },
  { id: "gluteus-maximus", nameZh: "臀大肌", nameEn: "Gluteus Maximus", nameLa: "Musculus gluteus maximus", group: "glutes", layer: "superficial", origin: "髂骨翼外面、骶骨、尾骨", insertion: "股骨臀肌粗隆", function: ["髋关节伸展","髋关节外旋"], exerciseIds: ["barbell-squat","deadlift","hip-thrust","lunge"], relatedNutrientIds: ["protein","creatine"], aliases: ["臀大","glutes"], meshNames: [] },
  { id: "gluteus-medius", nameZh: "臀中肌", nameEn: "Gluteus Medius", nameLa: "Musculus gluteus medius", group: "glutes", layer: "deep", origin: "髂骨翼外面", insertion: "股骨大转子", function: ["髋关节外展","骨盆稳定"], exerciseIds: ["lateral-band-walk"], relatedNutrientIds: ["protein"], aliases: ["臀中"], meshNames: [] },
  { id: "quadriceps", nameZh: "股四头肌", nameEn: "Quadriceps", nameLa: "Musculus quadriceps femoris", group: "quads", layer: "superficial", origin: "股直肌:髂前下棘;其余:股骨", insertion: "髌骨-胫骨粗隆", function: ["膝关节伸展","髋关节屈曲"], exerciseIds: ["barbell-squat","leg-press","leg-extension","lunge"], relatedNutrientIds: ["protein","creatine"], aliases: ["股四头","quads","大腿前侧"], meshNames: [] },
  { id: "hamstrings", nameZh: "腘绳肌", nameEn: "Hamstrings", nameLa: "Musculi ischiocrurales", group: "hamstrings", layer: "superficial", origin: "坐骨结节", insertion: "胫骨/腓骨", function: ["膝关节屈曲","髋关节伸展"], exerciseIds: ["romanian-deadlift","leg-curl"], relatedNutrientIds: ["protein"], aliases: ["大腿后侧"], meshNames: [] },
  { id: "gastrocnemius", nameZh: "腓肠肌", nameEn: "Gastrocnemius", nameLa: "Musculus gastrocnemius", group: "calves", layer: "superficial", origin: "股骨内/外侧髁", insertion: "跟骨", function: ["踝关节跖屈"], exerciseIds: ["standing-calf-raise"], relatedNutrientIds: ["protein"], aliases: ["小腿","calves"], meshNames: [] },
  { id: "soleus", nameZh: "比目鱼肌", nameEn: "Soleus", nameLa: "Musculus soleus", group: "calves", layer: "deep", origin: "腓骨/胫骨后面上部", insertion: "跟骨", function: ["踝关节跖屈"], exerciseIds: ["seated-calf-raise"], relatedNutrientIds: ["protein"], aliases: [], meshNames: [] },
  { id: "forearm-flexors", nameZh: "前臂屈肌群", nameEn: "Forearm Flexors", nameLa: "Musculi flexores antebrachii", group: "forearms", layer: "superficial", origin: "肱骨内上髁", insertion: "腕骨、掌骨、指骨", function: ["腕关节屈曲","手指屈曲"], exerciseIds: ["wrist-curl","farmer-walk"], relatedNutrientIds: ["protein"], aliases: ["前臂","forearm"], meshNames: [] },
];
