import { Nutrient } from '@/lib/types';

export const nutrients: Nutrient[] = [
  { id: "protein", nameZh: "蛋白质", nameEn: "Protein", type: "macronutrient", rda: { general: "0.8g/kg体重/天", athlete: "1.2-1.7g/kg体重/天", bodybuilding: "1.6-2.2g/kg体重/天" }, upperLimit: "3.5g/kg/天", deficiency: { shortTerm: ["肌肉流失","恢复变慢","疲劳乏力"], longTerm: ["基础代谢下降","免疫力严重下降","水肿","伤口愈合缓慢"], atRiskGroups: ["素食者","老年人","减脂过度者"], earlySigns: ["头发干枯易断","指甲脆弱","频繁生病"] }, excess: { shortTerm: ["腹胀、便秘","脱水"], longTerm: ["肾脏负担增加","钙流失风险"], atRiskGroups: ["肾病患者","痛风患者"] }, supplementIds: ["whey-protein","casein","bcaa"], foodIds: ["chicken-breast","beef-lean","egg","salmon","tofu","milk","shrimp","pork-lean"], relatedGoals: ["muscle_gain","fat_loss","strength"], aliases: ["蛋白质","protein"] },
  { id: "creatine", nameZh: "肌酸", nameEn: "Creatine", type: "other", rda: { general: "体内合成+饮食约1-2g/天", athlete: "3-5g/天" }, upperLimit: "5g/天长期安全", deficiency: { shortTerm: ["高强度运动表现下降","爆发力减少"], longTerm: ["肌肉力量和体积增长受阻"], atRiskGroups: ["素食者","老年人"], earlySigns: ["训练中更容易力竭"] }, excess: { shortTerm: ["腹胀","水潴留","腹泻(大剂量)"], longTerm: [], atRiskGroups: ["严重肾病患者"] }, supplementIds: ["creatine-monohydrate"], foodIds: ["beef-lean","salmon","pork-lean"], relatedGoals: ["muscle_gain","strength"], aliases: ["肌酸","creatine"] },
  { id: "carbohydrates", nameZh: "碳水化合物", nameEn: "Carbohydrates", type: "macronutrient", rda: { general: "总热量的45-65%", athlete: "5-10g/kg/天", bodybuilding: "3-5g/kg/天(增肌期)" }, upperLimit: "无明确上限", deficiency: { shortTerm: ["低血糖(头晕乏力)","运动表现下降"], longTerm: ["肌肉分解","代谢率下降"], atRiskGroups: ["低碳饮食者","耐力运动员"], earlySigns: ["训练无力","渴望甜食"] }, excess: { shortTerm: ["血糖波动","嗜睡"], longTerm: ["胰岛素抵抗","脂肪堆积","2型糖尿病风险"], atRiskGroups: ["糖尿病患者","久坐人群"] }, supplementIds: [], foodIds: ["rice","oats","sweet-potato","banana"], relatedGoals: ["muscle_gain","endurance"], aliases: ["碳水","carbs"] },
  { id: "fat", nameZh: "脂肪", nameEn: "Dietary Fat", type: "macronutrient", rda: { general: "总热量的20-35%", athlete: "总热量的20-30%" }, upperLimit: "饱和脂肪<10%总热量", deficiency: { shortTerm: ["脂溶性维生素吸收不良","皮肤干燥"], longTerm: ["激素水平下降","必需脂肪酸缺乏"], atRiskGroups: ["极端低脂饮食者"], earlySigns: ["皮肤干燥起皮","关节疼痛"] }, excess: { shortTerm: ["消化不适"], longTerm: ["肥胖","心血管疾病","脂肪肝","炎症增加"], atRiskGroups: ["心血管疾病家族史者","高血脂患者"] }, supplementIds: ["fish-oil"], foodIds: ["salmon","avocado","walnut","olive-oil","egg"], relatedGoals: ["muscle_gain"], aliases: ["脂肪","fat","油脂"] },
  { id: "vitamin-d", nameZh: "维生素D", nameEn: "Vitamin D", type: "vitamin", rda: { general: "600-800 IU/天", athlete: "1000-2000 IU/天" }, upperLimit: "4000 IU/天", deficiency: { shortTerm: ["疲劳乏力","肌肉酸痛","情绪低落"], longTerm: ["骨质疏松","免疫力下降","肌无力"], atRiskGroups: ["办公室人群","北方冬季居民","老年人"], earlySigns: ["反复感冒/感染"] }, excess: { shortTerm: ["恶心呕吐","食欲下降"], longTerm: ["高钙血症","肾结石","血管钙化","肾损伤"], atRiskGroups: ["补剂滥用者"], acuteSymptoms: ["恶心、呕吐"] }, supplementIds: ["vitamin-d3"], foodIds: ["salmon","egg","milk"], relatedGoals: ["muscle_gain","strength"], aliases: ["维D","维生素D","VD"] },
  { id: "vitamin-c", nameZh: "维生素C", nameEn: "Vitamin C", type: "vitamin", rda: { general: "100mg/天", athlete: "200-500mg/天" }, upperLimit: "2000mg/天", deficiency: { shortTerm: ["疲劳","牙龈出血","伤口愈合慢"], longTerm: ["坏血病","免疫力持续低下"], atRiskGroups: ["吸烟者","蔬菜水果摄入少者"], earlySigns: ["牙龈容易出血","皮肤易瘀伤"] }, excess: { shortTerm: ["腹泻","胃肠不适"], longTerm: ["肾结石风险(草酸盐)","铁过载"], atRiskGroups: ["肾结石病史者"] }, supplementIds: [], foodIds: ["orange","kiwi","broccoli","strawberry"], relatedGoals: ["muscle_gain"], aliases: ["维C","VC","抗坏血酸"] },
  { id: "iron", nameZh: "铁", nameEn: "Iron", type: "mineral", rda: { general: "男8mg/女18mg/天", athlete: "耐力运动员需增加30-50%" }, upperLimit: "45mg/天", deficiency: { shortTerm: ["疲劳无力","头晕","皮肤苍白"], longTerm: ["缺铁性贫血","免疫力下降","运动能力显著下降"], atRiskGroups: ["月经量多的女性","素食者","耐力运动员"], earlySigns: ["运动时气喘急促","面色苍白"] }, excess: { shortTerm: ["便秘","胃痛","恶心"], longTerm: ["铁过载/血色病","肝脏损害","糖尿病风险"], atRiskGroups: ["血色病基因携带者","男性"] }, supplementIds: [], foodIds: ["beef-lean","spinach","pork-lean","tofu"], relatedGoals: ["endurance"], aliases: ["铁","iron","Fe"] },
  { id: "calcium", nameZh: "钙", nameEn: "Calcium", type: "mineral", rda: { general: "800-1000mg/天", athlete: "1000-1200mg/天" }, upperLimit: "2500mg/天", deficiency: { shortTerm: ["肌肉抽筋","手指发麻"], longTerm: ["骨质疏松","骨折风险增加"], atRiskGroups: ["乳制品摄入少者","绝经后女性"], earlySigns: ["频繁抽筋","指甲脆弱"] }, excess: { shortTerm: ["便秘"], longTerm: ["肾结石","血管钙化风险","干扰铁/锌吸收"], atRiskGroups: ["肾结石病史者"], antagonism: ["高钙抑制铁和锌吸收"] }, supplementIds: [], foodIds: ["milk","tofu","broccoli","shrimp","spinach"], relatedGoals: ["strength"], aliases: ["钙","calcium","Ca"] },
  { id: "omega-3", nameZh: "Omega-3脂肪酸", nameEn: "Omega-3 Fatty Acids", type: "other", rda: { general: "EPA+DHA 250-500mg/天", athlete: "1-3g/天" }, upperLimit: "3g/天(补剂)", deficiency: { shortTerm: ["皮肤干燥","关节僵硬"], longTerm: ["慢性炎症","心血管疾病风险增加","认知功能下降"], atRiskGroups: ["不吃鱼者","素食者"], earlySigns: ["皮肤干燥粗糙"] }, excess: { shortTerm: ["鱼腥味嗳气","腹泻"], longTerm: ["出血倾向增加","免疫功能抑制(极高剂量)"], atRiskGroups: ["服用抗凝血药物者","即将手术者"] }, supplementIds: ["fish-oil"], foodIds: ["salmon","walnut"], relatedGoals: ["muscle_gain","fat_loss"], aliases: ["Omega3","欧米伽3","鱼油"] },
];
