import { Supplement } from '@/lib/types';

export const supplements: Supplement[] = [
  { id: "creatine-monohydrate", nameZh: "一水肌酸", nameEn: "Creatine Monohydrate", category: "performance", summary: "目前研究最充分、证据最强的运动补剂之一，安全有效提升力量和肌肉体积。", mechanism: { title: "磷酸肌酸系统", detail: "肌酸在体内与磷酸结合形成磷酸肌酸，在高强度运动中快速再合成ATP，延缓力竭。同时通过细胞水合作用促进肌肉蛋白质合成。" }, evidenceRating: "A", effects: [{ effect:"提升最大力量和爆发力", level:"强"},{ effect:"增加肌肉体积", level:"强"},{ effect:"改善高强度间歇运动表现", level:"强"},{ effect:"促进训练后恢复", level:"中"}], dosage: { loading:"冲击期(可选): 20g/天,分4次,持续5-7天", maintenance:"维持期: 3-5g/天", timing:"训练前后均可" }, safety: { sideEffects:["腹胀","水潴留"], contraindications:["严重肾病患者慎用"], longTerm:"长期使用安全性良好" }, foodSources:["beef-lean","salmon","pork-lean"], nutrientIds:["creatine"], relatedGoals:["muscle_gain","strength"], references:["Kreider RB, et al. JISSN. 2017"], aliases:["肌酸","creatine","一水肌酸"] },
  { id: "whey-protein", nameZh: "乳清蛋白", nameEn: "Whey Protein", category: "muscle", summary: "吸收最快的蛋白质来源，富含支链氨基酸，是增肌和恢复的核心补剂。", mechanism: { title: "快速氨基酸补充", detail: "乳清蛋白在摄入后20-40分钟内迅速消化吸收，血氨基酸浓度快速升高，有效刺激肌肉蛋白质合成(mTOR通路)。" }, evidenceRating: "A", effects: [{ effect:"促进训练后肌肉蛋白质合成", level:"强"},{ effect:"配合力量训练增加肌肉体积", level:"强"},{ effect:"减脂期保留瘦体重", level:"强"}], dosage: { maintenance:"每份20-40g，训练后30-60分钟内服用", timing:"训练后即刻" }, safety: { sideEffects:["腹胀/产气"], contraindications:["牛奶蛋白过敏者","严重乳糖不耐者"], longTerm:"推荐剂量内长期使用安全" }, foodSources:["milk","egg","chicken-breast"], nutrientIds:["protein"], relatedGoals:["muscle_gain","fat_loss"], references:["Phillips SM. Nutr Metab. 2016"], aliases:["蛋白粉","乳清","whey","乳清蛋白粉"] },
  { id: "casein", nameZh: "酪蛋白", nameEn: "Casein Protein", category: "muscle", summary: "慢速吸收蛋白，可持续释放氨基酸达7小时，适合睡前或长时间不进食时使用。", mechanism: { title: "缓释氨基酸供给", detail: "酪蛋白在胃酸环境中形成凝块，缓慢分解和吸收，持续释放氨基酸达6-7小时。" }, evidenceRating: "B", effects: [{ effect:"持续抑制肌肉蛋白分解", level:"强"},{ effect:"睡前服用改善夜间恢复", level:"中"},{ effect:"增加饱腹感", level:"强"}], dosage: { maintenance:"20-40g，睡前30分钟服用" }, safety: { sideEffects:["腹胀","便秘"], contraindications:["牛奶蛋白过敏者"], longTerm:"安全性良好" }, foodSources:["milk"], nutrientIds:["protein"], relatedGoals:["muscle_gain","fat_loss"], references:["Boirie Y, et al. PNAS. 1997"], aliases:["casein","酪蛋白","缓释蛋白"] },
  { id: "fish-oil", nameZh: "鱼油", nameEn: "Fish Oil", category: "health", summary: "富含EPA和DHA的Omega-3来源，具有抗炎、心血管保护和关节健康等多重益处。", mechanism: { title: "Omega-3抗炎通路", detail: "EPA和DHA嵌入细胞膜，竞争性抑制促炎因子生成，同时促进抗炎介质合成。通过PPARγ和NF-κB通路调节代谢和炎症。" }, evidenceRating: "A", effects: [{ effect:"减轻运动后炎症和肌肉酸痛", level:"中"},{ effect:"关节健康保护", level:"中"},{ effect:"心血管健康维护", level:"强"}], dosage: { maintenance:"EPA+DHA合计1-3g/天", timing:"随餐服用" }, safety: { sideEffects:["鱼腥味嗳气","轻度胃肠不适"], contraindications:["服用抗凝药者需医生评估","即将手术者(提前2周停药)"], longTerm:"3g/天以内长期安全" }, foodSources:["salmon"], nutrientIds:["omega-3"], relatedGoals:["muscle_gain","fat_loss"], references:["Calder PC. Biochem Soc Trans. 2017"], aliases:["鱼油","fish oil","omega3"] },
  { id: "vitamin-d3", nameZh: "维生素D3", nameEn: "Vitamin D3", category: "health", summary: "脂溶性维生素，对骨骼健康、免疫功能和肌肉功能至关重要，是中国人群最普遍缺乏的维生素之一。", mechanism: { title: "钙磷代谢与基因调控", detail: "活性维生素D与维生素D受体(VDR)结合，调控超过200个基因的表达。促进肠道钙磷吸收、骨骼矿化，并在肌肉细胞中直接促进蛋白质合成。" }, evidenceRating: "A", effects: [{ effect:"维持骨骼健康", level:"强"},{ effect:"提高免疫力", level:"强"},{ effect:"改善肌肉功能", level:"中"}], dosage: { maintenance:"1000-2000 IU/天", timing:"随含脂肪的餐服用" }, safety: { sideEffects:[], contraindications:["高钙血症患者"], longTerm:"4000 IU/天以内长期安全" }, foodSources:["salmon","egg","milk"], nutrientIds:["vitamin-d"], relatedGoals:["muscle_gain","strength"], references:["Holick MF. N Engl J Med. 2007"], aliases:["维D","维生素D","VD3"] },
  { id: "caffeine", nameZh: "咖啡因", nameEn: "Caffeine", category: "performance", summary: "最广泛使用的精神活性物质，有效提升运动表现、专注度和脂肪氧化。", mechanism: { title: "腺苷受体拮抗", detail: "咖啡因竞争性阻断大脑中的腺苷受体，抑制疲劳信号的传递。同时促进肾上腺素释放，增强脂肪分解和中枢神经系统兴奋性。" }, evidenceRating: "A", effects: [{ effect:"提升耐力运动表现", level:"强"},{ effect:"提高专注度和反应速度", level:"强"},{ effect:"促进脂肪氧化", level:"中"}], dosage: { maintenance:"运动前60分钟服用3-6mg/kg体重", timing:"训练前30-60分钟" }, safety: { sideEffects:["焦虑/心悸","失眠","胃肠刺激"], contraindications:["严重高血压","心律失常","焦虑症"], longTerm:"建议周期性停用(每8周停1-2周)" }, foodSources:[], nutrientIds:[], relatedGoals:["fat_loss","endurance"], references:["Goldstein ER, et al. JISSN. 2010"], aliases:["咖啡因","caffeine"] },
  { id: "beta-alanine", nameZh: "β-丙氨酸", nameEn: "Beta-Alanine", category: "performance", summary: "提升肌肉内肌肽水平，缓冲高强度运动产生的酸性物质，延缓疲劳。", mechanism: { title: "肌肽缓冲系统", detail: "β-丙氨酸是肌肽合成的限速前体。肌肉内肌肽作为pH缓冲剂，中和H+离子积累，延缓高强度运动中的酸中毒和疲劳。" }, evidenceRating: "A", effects: [{ effect:"提升高强度间歇运动表现", level:"强"},{ effect:"增加训练容量", level:"中"},{ effect:"延缓力竭时间", level:"强"}], dosage: { loading:"4-6g/天,分2-4次,持续2-4周", maintenance:"1.6-3.2g/天" }, safety: { sideEffects:["皮肤刺痛/发麻(无害)"], contraindications:[], longTerm:"长期使用安全性良好" }, foodSources:["chicken-breast","beef-lean"], nutrientIds:[], relatedGoals:["strength","endurance"], references:["Trexler ET, et al. JISSN. 2015"], aliases:["beta-alanine","β丙氨酸"] },
  { id: "bcaa", nameZh: "支链氨基酸", nameEn: "BCAA", category: "muscle", summary: "包含亮氨酸、异亮氨酸和缬氨酸。完整蛋白质(乳清)可能优于单独BCAA。", mechanism: { title: "mTOR通路激活", detail: "亮氨酸通过激活mTORC1信号通路刺激肌肉蛋白质合成。但BCAA单独缺乏其他必需氨基酸时，合成代谢效果有限。" }, evidenceRating: "B", effects: [{ effect:"可能减少运动引起的肌肉损伤", level:"中"},{ effect:"单独补充的增肌效果不如完整蛋白质", level:"强"}], dosage: { maintenance:"10-20g/天(性价比低，建议乳清蛋白)" }, safety: { sideEffects:[], contraindications:[], longTerm:"安全但性价比低" }, foodSources:["chicken-breast","egg","beef-lean","milk"], nutrientIds:["protein"], relatedGoals:["muscle_gain"], references:["Wolfe RR. JISSN. 2017"], aliases:["BCAA","支链氨基酸"] },
];

